### PR TITLE
Added ability to set and resolve hosts via user-specified nameservers

### PR DESCRIPTION
**Pull request by Script-Nomad**
This PR is meant to add the ability to specify nameservers. I wanted to make the DNS-lookup functionality of enumerid more tailored to situations where the pentester is not actually on the same local network as their target. This is especially helpful on VPNs or in situations where you can perform RID cycling, but you need to manually specify the nameserver. 

My use-case for this was because I was connected to a client via VPN, and my Linux VM was not being issued the correct nameservers. 

By default, enumerid will choose the target (the domain controller) as the parameter for the `-ns/--nameservers` argument unless a user chooses to change it.

This has been thoroughly tested on both local and remote-VPN connected networks, and I have not noted any breaking changes. The only major difference now is that enumerid must have the dnspython dependency as DNS resolution relies on the dnspython `resolver.Resolver()` rather than `socket`.

I added a new requirements.txt file for convenience.

### CODE REVIEW

**Comment by Gilks** [comment]
This sounds suspiciously like #1 where the FQDN option was added. Did you try using that option? I may be missing something but this sounds like the same feature.

**Comment by Script-Nomad** [comment]
No, specifically, this allows you to set the DNS server you are submitting your DNS requests to.

In the original `SAMR_GroupDump.get_ip()` function, the `socket.gethostbyname()` relied on the locally specified DNS nameservers to resolve hosts, in the case of Linux, that's whatever is configured in `/etc/resolv.conf`. 

This PR adds a new `nameservers` attribute to the `SAMR-GroupDump` class which consists of a list of nameservers. The default will always be the target dc-ip, unless the user specified the `-ns` flag and chose one or more nameservers manually. For resolving the IP addresses, the `dns.resolver.Resolver()` class is called to query these NS's. This was necessary because `socket.gethostbyname()` does not provide a way to send DNS queries to specific nameservers.

**Comment by Script-Nomad** [comment]
I'll also provide an example.

Say I'm connected to a VPN, and I'm doing `enumerid.py -r 515 (domain controllers)`. My /etc/resolv.conf file has not been updated with the nameserver for my VPN which should be `10.0.0.100`, and the domain should be `example.org`. Instead, my `/etc/resolv.conf` file only contains 8.8.8.8 (google public dns) and it does not have the correct NS Server.

When performing the get_ip() function, socket will send the DNS request to 8.8.8.8, which will fail to resolve an IP.

This update allows me to specifically target the domain controller for my DNS requests. Even with the FQDN update, there was no way to specify the NS you wanted to use. This update completes that functionality.

**Comment by Gilks** [comment]
Looks good. Sorry for the delay, merging

**Pull request merged**
